name: CI - Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'copilot/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || 'https://crkobgwfntptojxywjyg.supabase.co' }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNya29iZ3dmbnRwdG9qeHl3anlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NTQxNjUsImV4cCI6MjA3NjUzMDE2NX0.ZulC8ZCvR0PAYv77bNmEgs2y905NrbTOCw_9LxsTOK4' }}
        run: npm run build

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: |
            build.log
            npm-debug.log