name: CI - Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'copilot/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env from secrets (if provided)
        env:
          SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          if [ -n "$SUPABASE_URL" ]; then
            echo "VITE_SUPABASE_URL=$SUPABASE_URL" >> .env
          fi
          if [ -n "$SUPABASE_ANON_KEY" ]; then
            echo "VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          fi

      - name: Build
        run: npm run build

      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: |
            build.log
            npm-debug.log